apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app: template
spec:
  selector:
    matchLabels:
      app: template
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
      - name: template
        image: template:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
            requests:
                cpu: "500m"
            limits:
                cpu: "1000m"
